"""Standardized Master Skill Taxonomy and Synonym Reconciliation Database.

Based on O*NET and ESCO classifications tailored for software engineering,
data science, cloud architecture, and modern technical domains.
"""

from typing import Dict, List, Set, Optional

# Taxonomy Categories
CATEGORY_META: Dict[str, Dict[str, str]] = {
    "languages": {"label": "Languages", "color": "#3b82f6", "icon": "code"},
    "frontend": {"label": "Frontend", "color": "#ec4899", "icon": "layout"},
    "backend": {"label": "Backend", "color": "#10b981", "icon": "server"},
    "databases": {"label": "Databases & Storage", "color": "#f59e0b", "icon": "database"},
    "cloud_devops": {"label": "Cloud & DevOps", "color": "#6366f1", "icon": "cloud"},
    "data_ai": {"label": "Data & AI / ML", "color": "#8b5cf6", "icon": "cpu"},
    "architecture_testing": {"label": "Architecture & Practices", "color": "#14b8a6", "icon": "shield-check"},
    "soft_skills": {"label": "Soft & Leadership Skills", "color": "#f97316", "icon": "users"},
}

# Master Skill Catalog: canonical_name -> {category, description, difficulty}
MASTER_TAXONOMY: Dict[str, Dict[str, str]] = {
    # Programming Languages
    "Python": {"category": "languages", "description": "High-level, versatile programming language for web, scripting, and data science."},
    "JavaScript": {"category": "languages", "description": "Core dynamic language of the web platform."},
    "TypeScript": {"category": "languages", "description": "Typed superset of JavaScript adding compile-time static types."},
    "Go": {"category": "languages", "description": "Statically typed, compiled language engineered for high concurrency and microservices."},
    "Rust": {"category": "languages", "description": "Systems programming language emphasizing memory safety and zero-cost abstractions."},
    "Java": {"category": "languages", "description": "Object-oriented, class-based language widely used in enterprise backend architectures."},
    "C++": {"category": "languages", "description": "High-performance systems programming language with fine-grained memory management."},
    "C#": {"category": "languages", "description": "Modern object-oriented language developed by Microsoft for .NET."},
    "SQL": {"category": "languages", "description": "Standard declarative query language for relational database management."},
    "Bash/Shell": {"category": "languages", "description": "Unix shell scripting for automation and operating system operations."},
    "HTML5/CSS3": {"category": "languages", "description": "Fundamental markup and styling standards for web interfaces."},
    "Ruby": {"category": "languages", "description": "Dynamic, open-source programming language with a focus on simplicity and productivity."},
    "Kotlin": {"category": "languages", "description": "Modern cross-platform, statically typed language standard for Android development."},
    "PHP": {"category": "languages", "description": "Server-side scripting language designed specifically for web development."},
    "Swift": {"category": "languages", "description": "Apple's powerful, intuitive programming language for iOS/macOS systems."},
    "C": {"category": "languages", "description": "Foundational procedural systems programming language."},
    "R": {"category": "languages", "description": "Statistical computing and graphics programming language."},

    # Frontend
    "React": {"category": "frontend", "description": "Declarative component-based UI library developed by Meta."},
    "Next.js": {"category": "frontend", "description": "React production framework for SSR, static generation, and fullstack apps."},
    "Vue.js": {"category": "frontend", "description": "Progressive JavaScript framework for building user interfaces."},
    "Angular": {"category": "frontend", "description": "Opinionated TypeScript-based web application platform by Google."},
    "Tailwind CSS": {"category": "frontend", "description": "Utility-first CSS framework for rapid UI composition."},
    "Redux": {"category": "frontend", "description": "Predictable state container for JavaScript apps."},
    "Svelte": {"category": "frontend", "description": "Compiler-based UI framework producing minimal, high-speed runtime code."},
    "WebSockets": {"category": "frontend", "description": "Full-duplex real-time communication protocol for interactive web applications."},
    "Bootstrap": {"category": "frontend", "description": "Responsive front-end framework for mobile-first web development."},
    "jQuery": {"category": "frontend", "description": "Fast, feature-rich JavaScript DOM manipulation library."},
    "UI/UX Design": {"category": "frontend", "description": "User interface design, wireframing, user experience, and design systems."},
    "Figma": {"category": "frontend", "description": "Collaborative cloud-based interface design and prototyping tool."},

    # Backend
    "Node.js": {"category": "backend", "description": "Asynchronous event-driven JavaScript runtime built on Chrome's V8 engine."},
    "FastAPI": {"category": "backend", "description": "Modern, fast web framework for building APIs with Python based on type hints."},
    "Django": {"category": "backend", "description": "High-level Python web framework encouraging rapid development and clean design."},
    "Flask": {"category": "backend", "description": "Lightweight Python micro-framework for web applications and microservices."},
    "Express.js": {"category": "backend", "description": "Fast, unopinionated, minimalist web framework for Node.js."},
    "Spring Boot": {"category": "backend", "description": "Framework for creating stand-alone, production-grade Spring-based Java applications."},
    "GraphQL": {"category": "backend", "description": "Query language for APIs and runtime for executing queries with existing data."},
    "gRPC": {"category": "backend", "description": "High-performance, open-source universal RPC framework by Google."},
    "NestJS": {"category": "backend", "description": "Progressive TypeScript framework for building scalable enterprise server-side apps."},
    "ASP.NET": {"category": "backend", "description": "Microsoft web framework for building modern web apps and APIs."},
    "Laravel": {"category": "backend", "description": "Expressive PHP web application framework with MVC architecture."},

    # Databases & Storage
    "PostgreSQL": {"category": "databases", "description": "Advanced open-source object-relational database with strong ACID compliance."},
    "MySQL": {"category": "databases", "description": "Widely deployed open-source relational database system."},
    "MongoDB": {"category": "databases", "description": "Leading document-oriented NoSQL database for JSON-like data storage."},
    "Redis": {"category": "databases", "description": "In-memory data structure store used as a cache, database, and message broker."},
    "Elasticsearch": {"category": "databases", "description": "Distributed search and analytics engine for full-text search and log analytics."},
    "Cassandra": {"category": "databases", "description": "Highly scalable distributed NoSQL database designed to handle large volumes of data."},
    "DynamoDB": {"category": "databases", "description": "Fully managed proprietary NoSQL database service offered by Amazon AWS."},
    "SQLite": {"category": "databases", "description": "Self-contained, serverless, zero-configuration embedded SQL database engine."},
    "SQL Server": {"category": "databases", "description": "Microsoft relational database management system (MSSQL)."},
    "Oracle Database": {"category": "databases", "description": "Enterprise multi-model database management system."},
    "DBMS": {"category": "databases", "description": "Database management systems and relational schema design."},

    # Cloud & DevOps
    "Docker": {"category": "cloud_devops", "description": "Platform for developing, shipping, and running applications in isolated containers."},
    "Kubernetes": {"category": "cloud_devops", "description": "Open-source system for automating deployment, scaling, and management of containerized applications."},
    "AWS": {"category": "cloud_devops", "description": "Amazon Web Services comprehensive cloud computing platform."},
    "Google Cloud Platform (GCP)": {"category": "cloud_devops", "description": "Google suite of cloud computing services."},
    "Microsoft Azure": {"category": "cloud_devops", "description": "Microsoft cloud computing platform and infrastructure."},
    "CI/CD": {"category": "cloud_devops", "description": "Continuous Integration and Continuous Delivery/Deployment automation pipelines."},
    "GitHub Actions": {"category": "cloud_devops", "description": "Workflow automation platform directly integrated within GitHub."},
    "Terraform": {"category": "cloud_devops", "description": "Infrastructure as Code (IaC) tool for provisioning cloud resources declaratively."},
    "Linux": {"category": "cloud_devops", "description": "Open-source Unix-like operating system kernel powering cloud and enterprise infrastructure."},
    "Nginx": {"category": "cloud_devops", "description": "High-performance HTTP web server, reverse proxy, and load balancer."},
    "Ansible": {"category": "cloud_devops", "description": "Agentless automation tool for configuration management and application deployment."},

    # Data & AI / ML
    "Machine Learning": {"category": "data_ai", "description": "Algorithms that build mathematical models from sample data to make predictions."},
    "Deep Learning": {"category": "data_ai", "description": "Subfield of ML using multi-layered neural networks for complex pattern recognition."},
    "Natural Language Processing (NLP)": {"category": "data_ai", "description": "Field of AI focused on the interaction between computers and human language."},
    "PyTorch": {"category": "data_ai", "description": "Open-source deep learning framework based on the Torch library, developed by Meta."},
    "TensorFlow": {"category": "data_ai", "description": "End-to-end open source platform for machine learning developed by Google."},
    "Pandas": {"category": "data_ai", "description": "Fast, powerful, flexible open source data analysis and manipulation library for Python."},
    "NumPy": {"category": "data_ai", "description": "Fundamental package for scientific computing and multi-dimensional arrays with Python."},
    "Scikit-learn": {"category": "data_ai", "description": "Simple and efficient tools for predictive data analysis and classical machine learning in Python."},
    "Apache Spark": {"category": "data_ai", "description": "Unified analytics engine for large-scale distributed data processing."},
    "Data Pipelines / ETL": {"category": "data_ai", "description": "Extract, Transform, Load processes and architectures for batch/stream processing."},
    "Computer Vision": {"category": "data_ai", "description": "AI field training computers to interpret and understand the visual world."},
    "Large Language Models (LLMs)": {"category": "data_ai", "description": "Generative foundational models trained on vast corpora for NLP tasks and agents."},
    "Data Analysis": {"category": "data_ai", "description": "Inspecting, cleansing, transforming, and modeling data to discover insights."},
    "Excel": {"category": "data_ai", "description": "Spreadsheet analysis, formulas, pivot tables, and data modeling."},
    "Tableau": {"category": "data_ai", "description": "Interactive data visualization and business intelligence reporting software."},
    "Power BI": {"category": "data_ai", "description": "Microsoft business analytics and interactive visualization platform."},

    # Architecture & Practices
    "REST APIs": {"category": "architecture_testing", "description": "Representational State Transfer architectural style for networked web applications."},
    "Microservices": {"category": "architecture_testing", "description": "Architectural approach designing software as suites of independently deployable services."},
    "System Design": {"category": "architecture_testing", "description": "Architecture, module, and interface definition to satisfy specified engineering requirements."},
    "Unit Testing": {"category": "architecture_testing", "description": "Software testing methodology isolating individual units of source code for validation."},
    "Test-Driven Development (TDD)": {"category": "architecture_testing", "description": "Software development process relying on repetition of short test-first cycles."},
    "Agile/Scrum": {"category": "architecture_testing", "description": "Iterative project management and product development framework."},
    "Git": {"category": "architecture_testing", "description": "Distributed version control system for tracking changes in source code."},
    "Event-Driven Architecture": {"category": "architecture_testing", "description": "Software architecture paradigm orchestrating behavior around event emission and consumption."},
    "Data Structures & Algorithms": {"category": "architecture_testing", "description": "Foundational computing structures, computational complexity, and algorithmic design."},
    "Object-Oriented Programming (OOP)": {"category": "architecture_testing", "description": "Programming paradigm based on objects, classes, encapsulation, inheritance, and polymorphism."},
    "Software Testing & QA": {"category": "architecture_testing", "description": "Quality assurance, manual/automated testing, regression verification, and test cases."},
    "Operating Systems": {"category": "architecture_testing", "description": "Core operating system concepts including processes, memory management, and threads."},
    "Computer Networks": {"category": "architecture_testing", "description": "Network protocols, TCP/IP stack, HTTP/HTTPS, routing, and DNS architecture."},

    # Soft & Leadership Skills
    "Problem Solving": {"category": "soft_skills", "description": "Ability to identify, analyze, and implement robust solutions to complex technical challenges."},
    "Communication": {"category": "soft_skills", "description": "Clear and effective verbal, written, and cross-functional technical communication."},
    "Team Leadership": {"category": "soft_skills", "description": "Guiding, inspiring, and directing technical teams to achieve strategic goals."},
    "Mentorship": {"category": "soft_skills", "description": "Guiding and developing junior/mid-level engineers through coaching and code reviews."},
    "Cross-functional Collaboration": {"category": "soft_skills", "description": "Partnering productively with product managers, designers, and business stakeholders."},
    "Critical Thinking": {"category": "soft_skills", "description": "Objective analysis and evaluation of engineering trade-offs and architectural decisions."},
    "Project Management": {"category": "soft_skills", "description": "Planning, executing, and closing technical projects within scope and timeline constraints."},
    "Teamwork & Collaboration": {"category": "soft_skills", "description": "Working productively within engineering teams and contributing to shared goals."},
    "Time Management": {"category": "soft_skills", "description": "Prioritizing tasks, meeting engineering sprint deadlines, and managing bandwidth."},
    "Adaptability": {"category": "soft_skills", "description": "Quickly learning new technologies, tools, and pivoting with evolving requirements."},
    "Analytical Thinking": {"category": "soft_skills", "description": "Systematic breakdown of complex problems and data-informed decision making."},
}

# Synonym and Alias Reconciliation Mapping (lowercase alias -> Canonical Name)
SYNONYM_MAP: Dict[str, str] = {
    # Languages
    "python": "Python",
    "python3": "Python",
    "py": "Python",
    "javascript": "JavaScript",
    "js": "JavaScript",
    "ecmascript": "JavaScript",
    "es6": "JavaScript",
    "es2015": "JavaScript",
    "typescript": "TypeScript",
    "ts": "TypeScript",
    "golang": "Go",
    "go lang": "Go",
    "go language": "Go",
    "rust": "Rust",
    "rust-lang": "Rust",
    "java": "Java",
    "java 11": "Java",
    "java 17": "Java",
    "java 21": "Java",
    "c++": "C++",
    "cpp": "C++",
    "cplusplus": "C++",
    "c#": "C#",
    "csharp": "C#",
    ".net": "C#",
    "sql": "SQL",
    "structured query language": "SQL",
    "bash": "Bash/Shell",
    "shell": "Bash/Shell",
    "zsh": "Bash/Shell",
    "shell scripting": "Bash/Shell",
    "html": "HTML5/CSS3",
    "html5": "HTML5/CSS3",
    "css": "HTML5/CSS3",
    "css3": "HTML5/CSS3",
    "html/css": "HTML5/CSS3",
    "ruby": "Ruby",
    "ruby on rails": "Ruby",
    "kotlin": "Kotlin",
    "php": "PHP",
    "swift": "Swift",
    "c": "C",
    "c language": "C",
    "c programming": "C",
    "ansi c": "C",
    "embedded c": "C",
    "r": "R",
    "r programming": "R",
    "r language": "R",
    "r-lang": "R",

    # Frontend
    "react": "React",
    "reactjs": "React",
    "react.js": "React",
    "next": "Next.js",
    "nextjs": "Next.js",
    "next.js": "Next.js",
    "vue": "Vue.js",
    "vuejs": "Vue.js",
    "vue.js": "Vue.js",
    "angular": "Angular",
    "angularjs": "Angular",
    "angular 2+": "Angular",
    "tailwind": "Tailwind CSS",
    "tailwindcss": "Tailwind CSS",
    "tailwind css": "Tailwind CSS",
    "redux": "Redux",
    "redux toolkit": "Redux",
    "svelte": "Svelte",
    "sveltekit": "Svelte",
    "websocket": "WebSockets",
    "websockets": "WebSockets",
    "bootstrap": "Bootstrap",
    "bootstrap 4": "Bootstrap",
    "bootstrap 5": "Bootstrap",
    "bootstrap css": "Bootstrap",
    "jquery": "jQuery",
    "ui/ux": "UI/UX Design",
    "ui/ux design": "UI/UX Design",
    "ui design": "UI/UX Design",
    "ux design": "UI/UX Design",
    "user interface": "UI/UX Design",
    "user experience": "UI/UX Design",
    "wireframing": "UI/UX Design",
    "prototyping": "UI/UX Design",
    "figma": "Figma",

    # Backend
    "node": "Node.js",
    "nodejs": "Node.js",
    "node.js": "Node.js",
    "fastapi": "FastAPI",
    "fast api": "FastAPI",
    "django": "Django",
    "django rest framework": "Django",
    "drf": "Django",
    "flask": "Flask",
    "express": "Express.js",
    "expressjs": "Express.js",
    "express.js": "Express.js",
    "spring": "Spring Boot",
    "spring boot": "Spring Boot",
    "springboot": "Spring Boot",
    "graphql": "GraphQL",
    "grpc": "gRPC",
    "nestjs": "NestJS",
    "nest.js": "NestJS",
    "asp.net": "ASP.NET",
    "asp.net core": "ASP.NET",
    ".net core": "ASP.NET",
    "dotnet core": "ASP.NET",
    "aspnet": "ASP.NET",
    "laravel": "Laravel",
    "php laravel": "Laravel",

    # Databases
    "postgres": "PostgreSQL",
    "postgresql": "PostgreSQL",
    "psql": "PostgreSQL",
    "mysql": "MySQL",
    "mongo": "MongoDB",
    "mongodb": "MongoDB",
    "redis": "Redis",
    "elasticsearch": "Elasticsearch",
    "elastic search": "Elasticsearch",
    "cassandra": "Cassandra",
    "dynamodb": "DynamoDB",
    "dynamo db": "DynamoDB",
    "sqlite": "SQLite",
    "sqlite3": "SQLite",
    "sql server": "SQL Server",
    "mssql": "SQL Server",
    "ms sql": "SQL Server",
    "microsoft sql server": "SQL Server",
    "oracle": "Oracle Database",
    "oracle db": "Oracle Database",
    "oracle database": "Oracle Database",
    "oracle sql": "Oracle Database",
    "dbms": "DBMS",
    "rdbms": "DBMS",
    "database management": "DBMS",
    "relational database": "DBMS",
    "database management systems": "DBMS",

    # Cloud & DevOps
    "docker": "Docker",
    "containerization": "Docker",
    "containers": "Docker",
    "kubernetes": "Kubernetes",
    "k8s": "Kubernetes",
    "aws": "AWS",
    "amazon web services": "AWS",
    "gcp": "Google Cloud Platform (GCP)",
    "google cloud": "Google Cloud Platform (GCP)",
    "google cloud platform": "Google Cloud Platform (GCP)",
    "azure": "Microsoft Azure",
    "microsoft azure": "Microsoft Azure",
    "ci/cd": "CI/CD",
    "cicd": "CI/CD",
    "continuous integration": "CI/CD",
    "continuous deployment": "CI/CD",
    "github actions": "GitHub Actions",
    "gh actions": "GitHub Actions",
    "terraform": "Terraform",
    "linux": "Linux",
    "unix": "Linux",
    "ubuntu": "Linux",
    "nginx": "Nginx",
    "ansible": "Ansible",
    "gitlab": "Git",
    "bitbucket": "Git",
    "vcs": "Git",

    # Data & AI / ML
    "machine learning": "Machine Learning",
    "ml": "Machine Learning",
    "deep learning": "Deep Learning",
    "dl": "Deep Learning",
    "natural language processing": "Natural Language Processing (NLP)",
    "nlp": "Natural Language Processing (NLP)",
    "pytorch": "PyTorch",
    "torch": "PyTorch",
    "tensorflow": "TensorFlow",
    "tf": "TensorFlow",
    "pandas": "Pandas",
    "numpy": "NumPy",
    "scikit-learn": "Scikit-learn",
    "sklearn": "Scikit-learn",
    "spark": "Apache Spark",
    "apache spark": "Apache Spark",
    "etl": "Data Pipelines / ETL",
    "data pipelines": "Data Pipelines / ETL",
    "data pipeline": "Data Pipelines / ETL",
    "computer vision": "Computer Vision",
    "cv": "Computer Vision",
    "llm": "Large Language Models (LLMs)",
    "llms": "Large Language Models (LLMs)",
    "large language models": "Large Language Models (LLMs)",
    "data analysis": "Data Analysis",
    "data analytics": "Data Analysis",
    "exploratory data analysis": "Data Analysis",
    "eda": "Data Analysis",
    "data mining": "Data Analysis",
    "excel": "Excel",
    "microsoft excel": "Excel",
    "ms excel": "Excel",
    "spreadsheets": "Excel",
    "spreadsheet": "Excel",
    "advanced excel": "Excel",
    "vlookup": "Excel",
    "pivot tables": "Excel",
    "tableau": "Tableau",
    "power bi": "Power BI",
    "powerbi": "Power BI",
    "power-bi": "Power BI",
    "data science": "Machine Learning",

    # Architecture & Practices
    "rest": "REST APIs",
    "rest api": "REST APIs",
    "rest apis": "REST APIs",
    "restful": "REST APIs",
    "restful api": "REST APIs",
    "restful apis": "REST APIs",
    "microservices": "Microservices",
    "micro-services": "Microservices",
    "microservice": "Microservices",
    "system design": "System Design",
    "distributed systems": "System Design",
    "unit testing": "Unit Testing",
    "testing": "Unit Testing",
    "tdd": "Test-Driven Development (TDD)",
    "test driven development": "Test-Driven Development (TDD)",
    "test-driven development": "Test-Driven Development (TDD)",
    "agile": "Agile/Scrum",
    "scrum": "Agile/Scrum",
    "agile/scrum": "Agile/Scrum",
    "git": "Git",
    "github": "Git",
    "version control": "Git",
    "event driven": "Event-Driven Architecture",
    "event-driven architecture": "Event-Driven Architecture",
    "kafka": "Event-Driven Architecture",
    "data structures": "Data Structures & Algorithms",
    "data structures and algorithms": "Data Structures & Algorithms",
    "data structures & algorithms": "Data Structures & Algorithms",
    "dsa": "Data Structures & Algorithms",
    "oop": "Object-Oriented Programming (OOP)",
    "oops": "Object-Oriented Programming (OOP)",
    "object-oriented programming": "Object-Oriented Programming (OOP)",
    "object oriented programming": "Object-Oriented Programming (OOP)",
    "object oriented": "Object-Oriented Programming (OOP)",
    "software testing": "Software Testing & QA",
    "qa": "Software Testing & QA",
    "quality assurance": "Software Testing & QA",
    "manual testing": "Software Testing & QA",
    "automation testing": "Software Testing & QA",
    "selenium": "Software Testing & QA",
    "cypress": "Software Testing & QA",
    "pytest": "Software Testing & QA",
    "test cases": "Software Testing & QA",
    "operating systems": "Operating Systems",
    "operating system": "Operating Systems",
    "os concepts": "Operating Systems",
    "computer networks": "Computer Networks",
    "networking": "Computer Networks",
    "tcp/ip": "Computer Networks",

    # Soft & Leadership Skills
    "problem solving": "Problem Solving",
    "problem-solving": "Problem Solving",
    "troubleshooting": "Problem Solving",
    "debugging": "Problem Solving",
    "problem solver": "Problem Solving",
    "analytical thinking": "Analytical Thinking",
    "analytical skills": "Analytical Thinking",
    "communication": "Communication",
    "verbal communication": "Communication",
    "written communication": "Communication",
    "oral communication": "Communication",
    "presentation": "Communication",
    "presentation skills": "Communication",
    "interpersonal skills": "Communication",
    "leadership": "Team Leadership",
    "team leadership": "Team Leadership",
    "team lead": "Team Leadership",
    "mentorship": "Mentorship",
    "mentoring": "Mentorship",
    "coaching": "Mentorship",
    "cross-functional collaboration": "Cross-functional Collaboration",
    "cross functional": "Cross-functional Collaboration",
    "stakeholder management": "Cross-functional Collaboration",
    "critical thinking": "Critical Thinking",
    "project management": "Project Management",
    "teamwork": "Teamwork & Collaboration",
    "team work": "Teamwork & Collaboration",
    "team player": "Teamwork & Collaboration",
    "collaboration": "Teamwork & Collaboration",
    "collaborative": "Teamwork & Collaboration",
    "collaborating": "Teamwork & Collaboration",
    "time management": "Time Management",
    "prioritization": "Time Management",
    "multitasking": "Time Management",
    "punctuality": "Time Management",
    "adaptability": "Adaptability",
    "adaptable": "Adaptability",
    "flexible": "Adaptability",
    "flexibility": "Adaptability",
    "quick learner": "Adaptability",
    "fast learner": "Adaptability",
}


def normalize_skill(term: str) -> Optional[str]:
    """Reconcile and normalize any skill alias or variation to canonical name.

    Returns:
        Canonical skill name if recognized in taxonomy, else None.
    """
    clean_term = term.strip().lower()
    return SYNONYM_MAP.get(clean_term)


def get_skill_metadata(canonical_name: str) -> Dict[str, str]:
    """Get metadata (category, description) for a canonical skill name."""
    return MASTER_TAXONOMY.get(
        canonical_name,
        {"category": "languages", "description": "Technical competency"}
    )
